import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SmashBase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> 
        Smashbase
        </h1>

        <p className={styles.description}>
          A collection of tools to assist in the organization of smash tournaments
        </p>
        <p>Work is still in progress, please forgive our appearance for the time being</p>

        <div className={styles.grid}>
          <Link href="/SeedingApp" className={styles.card}>Seeding Tool &rarr;</Link>

          
            <p>Automatically seed using our seeding tool. 
              Players are sorted using an acurate algorithm and then separated
              based on set history, carpools, and more. We even push seeding to start.gg so you don't have to! </p>
        
          <a href="/SeedingApp" className={styles.card}>
            <h2>Seeding &rarr;</h2>
            <p>Automatically seed using our seeding tool</p>
          </a>


          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Event Finder &rarr;</h2>
            <p>Find evends near you utilizing your location or by inputting coordinates. You can even set the distance from that location and we will show you all events from that distance.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Ranking &rarr;</h2>
            <p>Find a player and see how they measure up to the rest of the competition</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>About Us & Contact &rarr;</h2>
            <p>
              Learn about us or contact us.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
